"""Add connection_profiles and credential_references tables

Revision ID: 26f037b4e759
Revises: af439877fe3a
Create Date: 2026-03-18 16:00:10.939480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26f037b4e759'
down_revision: Union[str, Sequence[str], None] = 'af439877fe3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credential_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('username_env_var', sa.String(length=100), nullable=False),
    sa.Column('password_env_var', sa.String(length=100), nullable=True),
    sa.Column('ssh_key_env_var', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credential_references_id'), 'credential_references', ['id'], unique=False)
    op.create_index(op.f('ix_credential_references_name'), 'credential_references', ['name'], unique=True)
    op.create_table('connection_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('applies_to_role', sa.String(length=50), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('topology', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connection_profiles_applies_to_role'), 'connection_profiles', ['applies_to_role'], unique=False)
    op.create_index(op.f('ix_connection_profiles_device_id'), 'connection_profiles', ['device_id'], unique=False)
    op.create_index(op.f('ix_connection_profiles_id'), 'connection_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_connection_profiles_name'), 'connection_profiles', ['name'], unique=True)
    op.create_index(op.f('ix_connection_profiles_priority'), 'connection_profiles', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connection_profiles_priority'), table_name='connection_profiles')
    op.drop_index(op.f('ix_connection_profiles_name'), table_name='connection_profiles')
    op.drop_index(op.f('ix_connection_profiles_id'), table_name='connection_profiles')
    op.drop_index(op.f('ix_connection_profiles_device_id'), table_name='connection_profiles')
    op.drop_index(op.f('ix_connection_profiles_applies_to_role'), table_name='connection_profiles')
    op.drop_table('connection_profiles')
    op.drop_index(op.f('ix_credential_references_name'), table_name='credential_references')
    op.drop_index(op.f('ix_credential_references_id'), table_name='credential_references')
    op.drop_table('credential_references')
    # ### end Alembic commands ###
