"""add_device_import_history_table

Revision ID: af439877fe3a
Revises: bc56825a8e66
Create Date: 2026-03-18 13:27:06.001165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af439877fe3a'
down_revision: Union[str, Sequence[str], None] = 'bc56825a8e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_import_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('inserted', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('changes_summary', sa.JSON(), nullable=True),
    sa.Column('performed_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_import_history_id'), 'device_import_history', ['id'], unique=False)
    op.create_index(op.f('ix_device_import_history_imported_at'), 'device_import_history', ['imported_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_import_history_imported_at'), table_name='device_import_history')
    op.drop_index(op.f('ix_device_import_history_id'), table_name='device_import_history')
    op.drop_table('device_import_history')
    # ### end Alembic commands ###
