"""add_device_outputs_and_facts_tables

Revision ID: bc56825a8e66
Revises: d1989e15b2d5
Create Date: 2026-03-17 14:07:15.713120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc56825a8e66'
down_revision: Union[str, Sequence[str], None] = 'd1989e15b2d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('fact_type', sa.String(length=100), nullable=False),
    sa.Column('fact_key', sa.String(length=200), nullable=True),
    sa.Column('fact_data', sa.JSON(), nullable=False),
    sa.Column('collection_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_command', sa.String(length=500), nullable=True),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_facts_collection_timestamp'), 'device_facts', ['collection_timestamp'], unique=False)
    op.create_index(op.f('ix_device_facts_device_id'), 'device_facts', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_facts_fact_key'), 'device_facts', ['fact_key'], unique=False)
    op.create_index(op.f('ix_device_facts_fact_type'), 'device_facts', ['fact_type'], unique=False)
    op.create_index(op.f('ix_device_facts_id'), 'device_facts', ['id'], unique=False)
    op.create_index(op.f('ix_device_facts_task_id'), 'device_facts', ['task_id'], unique=False)
    op.create_table('device_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('command', sa.String(length=500), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('collection_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.Column('minio_bucket', sa.String(length=100), nullable=True),
    sa.Column('minio_object_key', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_outputs_collection_timestamp'), 'device_outputs', ['collection_timestamp'], unique=False)
    op.create_index(op.f('ix_device_outputs_device_id'), 'device_outputs', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_outputs_id'), 'device_outputs', ['id'], unique=False)
    op.create_index(op.f('ix_device_outputs_task_id'), 'device_outputs', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_outputs_task_id'), table_name='device_outputs')
    op.drop_index(op.f('ix_device_outputs_id'), table_name='device_outputs')
    op.drop_index(op.f('ix_device_outputs_device_id'), table_name='device_outputs')
    op.drop_index(op.f('ix_device_outputs_collection_timestamp'), table_name='device_outputs')
    op.drop_table('device_outputs')
    op.drop_index(op.f('ix_device_facts_task_id'), table_name='device_facts')
    op.drop_index(op.f('ix_device_facts_id'), table_name='device_facts')
    op.drop_index(op.f('ix_device_facts_fact_type'), table_name='device_facts')
    op.drop_index(op.f('ix_device_facts_fact_key'), table_name='device_facts')
    op.drop_index(op.f('ix_device_facts_device_id'), table_name='device_facts')
    op.drop_index(op.f('ix_device_facts_collection_timestamp'), table_name='device_facts')
    op.drop_table('device_facts')
    # ### end Alembic commands ###
