#!/usr/bin/env python3
"""Bulk device collection script.

Collects show version and show run from all devices in specified roles.
Uses Celery workers with EEP protection for reliable, concurrent collection.

Usage:
    # Default: 10 concurrent tasks, all supported roles
    python scripts/bulk_collect.py
    
    # Custom concurrency
    python scripts/bulk_collect.py --concurrency 20
    
    # Specific roles only
    python scripts/bulk_collect.py --roles EN,AN,CN
    
    # Test dry run (no actual collection)
    python scripts/test_bulk_collect.py --roles EN,AN,CN
"""

import argparse
import asyncio
import json
import logging
import sys
import time
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.session import SessionLocal
from app.models.device import Device
from workers.celery_app import celery_app
from workers.tasks.device_tasks import collect_device_data


# Setup logging
logger = logging.getLogger(__name__)


# Supported roles
DEFAULT_ROLES = ["EN", "AN", "CN", "IGW", "RR", "P"]

# Platform mapping: Database platform -> Netmiko device_type
PLATFORM_MAP = {
    # Cisco IOS-XR devices (ASR, NCS, CRS, XRv)
    "Cisco ASR 9006 Router": "cisco_xr",
    "Cisco ASR 9010 Router": "cisco_xr",
    "Cisco ASR 9902 Router": "cisco_xr",
    "Cisco ASR 9906 Router": "cisco_xr",
    "Cisco ASR 9910 Router": "cisco_xr",
    "Cisco ASR 9912 Router": "cisco_xr",
    "Cisco ASR 9922 Router": "cisco_xr",
    "Cisco NCS 5504": "cisco_xr",
    "Cisco NCS 5508": "cisco_xr",
    "Cisco NCS 540X-16Z4G8Q2C-D Router": "cisco_xr",
    "Cisco NCS 540X-6Z18G-SYS-D Router": "cisco_xr",
    "Cisco NCS 55A2-MOD-S": "cisco_xr",
    "Cisco IOS XRv 9000 Router": "cisco_xr",
    "Cisco CRS-8/S Router": "cisco_xr",
    
    # Cisco IOS devices (ASR 1000 series)
    "Cisco ASR 1002-HX Router": "cisco_ios",
    "Cisco ASR 1006-X Router": "cisco_ios",
    
    # Add more mappings as needed
}


def normalize_platform(platform: str | None) -> str:
    """Map database platform to Netmiko device_type."""
    if not platform:
        return "cisco_xr"  # Default
    
    # Check if exact match exists
    if platform in PLATFORM_MAP:
        return PLATFORM_MAP[platform]
    
    # Fallback: Try to guess based on platform string
    platform_lower = platform.lower()
    if any(x in platform_lower for x in ["asr 9", "ncs 5", "ncs 55", "xrv", "crs"]):
        return "cisco_xr"
    elif any(x in platform_lower for x in ["asr 1", "isr"]):
        return "cisco_ios"
    elif "nexus" in platform_lower or "nxos" in platform_lower:
        return "cisco_nxos"
    
    # Default to cisco_xr for unknown Cisco devices
    return "cisco_xr"


def load_commands(filepath: str) -> dict[str, str]:
    """
    Load commands from text file. One command per line.
    
    Args:
        filepath: Path to commands file
    
    Returns:
        Dictionary mapping sanitized keys to command strings
        
    Format:
        - One command per line
        - Lines starting with # are comments (ignored)
        - Blank lines are ignored
        - Command keys are auto-generated by lowercasing and replacing spaces with underscores
    
    Example:
        show version        → {"show_version": "show version"}
        show ip route       → {"show_ip_route": "show ip route"}
        # comment line      → (ignored)
    """
    commands = {}
    
    with open(filepath, 'r') as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()
            
            # Skip blank lines and comments
            if not line or line.startswith("#"):
                continue
            
            # Generate key from command (lowercase, spaces to underscores)
            key = line.lower().replace(" ", "_")
            
            # Check for duplicates
            if key in commands:
                print(f"  ⚠ Warning: Duplicate command at line {line_num}: '{line}'")
                continue
            
            commands[key] = line
    
    return commands


def load_profiles(profile_names: str, commands_dir: Path = None) -> dict[str, str]:
    """
    Load commands from one or more profile files and merge them.
    
    Args:
        profile_names: Comma-separated profile names (e.g., "healthcheck,security_audit")
        commands_dir: Directory containing profile files (default: project_root/commands)
    
    Returns:
        Merged dictionary of commands with duplicates removed
    """
    if commands_dir is None:
        commands_dir = project_root / "commands"
    
    all_commands = {}
    profiles = [p.strip() for p in profile_names.split(",")]
    
    print(f"\nLoading command profiles:")
    for profile_name in profiles:
        profile_file = commands_dir / f"{profile_name}.txt"
        
        if not profile_file.exists():
            print(f"  ✗ Profile not found: {profile_name}")
            print(f"    Expected: {profile_file}")
            sys.exit(1)
        
        # Load commands from profile
        profile_commands = load_commands(str(profile_file))
        
        # Track duplicates for reporting
        duplicates = set(profile_commands.keys()) & set(all_commands.keys())
        new_commands = len(profile_commands) - len(duplicates)
        
        all_commands.update(profile_commands)
        
        print(f"  ✓ {profile_name}: {len(profile_commands)} commands ({new_commands} new, {len(duplicates)} duplicate)")
    
    print(f"\nTotal unique commands: {len(all_commands)}")
    return all_commands


class BulkCollector:
    """Manages bulk device collection."""
    
    def __init__(self, concurrency: int = 10, roles: list[str] = None, limit: int = None, commands: dict[str, str] = None, platform: str = None):
        self.concurrency = concurrency
        self.roles = roles or DEFAULT_ROLES
        self.limit = limit
        self.commands = commands or {}
        self.platform = platform  # Platform filter (substring match)
        
        # Output directories (dynamic based on commands)
        self.base_dir = project_root / "collection_logs"
        self.error_dir = self.base_dir / "errors"
        self.command_dirs = {}  # Will be populated in setup_directories
        
        # Metrics
        self.metrics = {
            "start_time": None,
            "end_time": None,
            "total_devices": 0,
            "successful_devices": 0,
            "failed_devices": 0,
            "commands_collected": defaultdict(int),
            "errors_by_type": defaultdict(int),
            "concurrency": concurrency,
            "roles": roles or DEFAULT_ROLES,
            "commands": list(self.commands.values()),
        }
    
    def setup_directories(self):
        """Create output directories dynamically based on commands."""
        print("\nSetting up directories...")
        
        # Create error directory
        self.error_dir.mkdir(parents=True, exist_ok=True)
        print(f"  ✓ {self.error_dir}")
        
        # Create directory for each command
        for cmd_key in self.commands.keys():
            cmd_dir = self.base_dir / cmd_key
            cmd_dir.mkdir(parents=True, exist_ok=True)
            self.command_dirs[cmd_key] = cmd_dir
            print(f"  ✓ {cmd_dir}")
    
    async def fetch_devices(self) -> list[Device]:
        """Fetch devices from database."""
        print(f"\nFetching devices with roles: {', '.join(self.roles)}...")
        
        async with SessionLocal() as session:
            stmt = select(Device).where(Device.role.in_(self.roles))
            
            # Apply platform filter if specified
            if self.platform:
                stmt = stmt.where(Device.platform.contains(self.platform))
                print(f"  Platform filter: {self.platform}")
            
            # Apply limit if specified
            if self.limit:
                stmt = stmt.limit(self.limit)
            
            result = await session.execute(stmt)
            devices = result.scalars().all()
            
            # Convert to list of dicts for JSON serialization
            device_list = [
                {
                    "id": d.id,
                    "hostname": d.hostname,
                    "mgmt_ip": d.mgmt_ip,
                    "role": d.role,
                    "platform": normalize_platform(d.platform),  # Map to Netmiko device_type
                    "raw_platform": d.platform,  # Keep original for reference
                }
                for d in devices
            ]
            
            print(f"  ✓ Found {len(device_list)} devices")
            
            # Show breakdown by role
            by_role = defaultdict(int)
            for d in device_list:
                by_role[d["role"]] += 1
            
            print("\n  Breakdown by role:")
            for role, count in sorted(by_role.items()):
                print(f"    {role}: {count}")
            
            return device_list
    
    def check_celery_workers(self) -> bool:
        """Check if Celery workers are running."""
        print("\nChecking Celery workers...")
        
        try:
            inspect = celery_app.control.inspect()
            active_workers = inspect.active()
            
            if not active_workers:
                print("\n  ✗ No active Celery workers found!")
                print("\n  Please start a worker first:")
                print("    ./start_worker.sh")
                print("\n  Or manually:")
                print("    celery -A workers.celery_app worker --pool=threads --concurrency=50")
                return False
            
            print(f"  ✓ Found {len(active_workers)} active worker(s)")
            for worker_name, tasks in active_workers.items():
                print(f"    - {worker_name}: {len(tasks)} active tasks")
            
            return True
            
        except Exception as e:
            print(f"\n  ✗ Cannot connect to Celery: {e}")
            print("\n  Please ensure:")
            print("    1. Redis is running: cd infra/docker && docker compose up -d")
            print("    2. Celery worker is running: ./start_worker.sh")
            return False
    
    def submit_device_collection(self, device: dict) -> tuple[str, Any]:
        """Submit collection task for a device."""
        # Generate session log filename
        session_log = self.error_dir / f"{device['hostname']}_{device['mgmt_ip']}_session.log"
        
        # Prepare command list: terminal length 0 + user commands
        command_list = ["terminal length 0"] + list(self.commands.values())
        
        # Submit task
        result = collect_device_data.apply_async(
            args=[
                device["id"],
                device["hostname"],
                device["mgmt_ip"],
                device["platform"],
                command_list,
            ],
            kwargs={
                "session_log": str(session_log),
            },
            queue="devices"
        )
        
        return result.id, result
    
    def save_command_output(self, device: dict, command_key: str, result_metadata: dict):
        """
        Process command result metadata.
        
        With the new approach, outputs are saved directly during collection.
        This method just verifies the file was saved and updates metrics.
        
        Args:
            device: Device dict
            command_key: Command key (e.g., 'show_version')
            result_metadata: Result dict with metadata (no output text)
        """
        # File should already exist (saved during collection)
        if result_metadata.get("saved_to_disk"):
            output_file = result_metadata.get("output_file")
            if output_file and Path(output_file).exists():
                self.metrics["commands_collected"][command_key] += 1
                logger.debug(f"Verified output file: {output_file}")
            else:
                logger.warning(f"Output file not found: {output_file}")
        else:
            # Terminal length 0 or other non-saved commands
            self.metrics["commands_collected"][command_key] += 1
    
    def log_error(self, device: dict, error_type: str, error_message: str):
        """Log collection error."""
        error_file = self.error_dir / f"{device['hostname']}_{device['mgmt_ip']}_error.log"
        
        with open(error_file, 'w') as f:
            f.write(f"Device: {device['hostname']} ({device['mgmt_ip']})\n")
            f.write(f"Role: {device['role']}\n")
            f.write(f"Error Type: {error_type}\n")
            f.write(f"Timestamp: {datetime.now().isoformat()}\n")
            f.write(f"\n{error_message}\n")
        
        self.metrics["errors_by_type"][error_type] += 1
    
    async def collect_batch(self, devices: list[dict]) -> dict:
        """Collect from a batch of devices."""
        batch_results = {
            "submitted": 0,
            "successful": 0,
            "failed": 0,
        }
        
        # Submit all tasks
        print(f"\n  Submitting {len(devices)} tasks...")
        tasks = {}
        for device in devices:
            task_id, result = self.submit_device_collection(device)
            tasks[task_id] = {
                "device": device,
                "result": result,
            }
        
        batch_results["submitted"] = len(tasks)
        print(f"  ✓ Submitted {len(tasks)} tasks")
        
        # Wait for results
        print(f"  Waiting for results...")
        pending = set(tasks.keys())
        
        while pending:
            completed = set()
            
            for task_id in pending:
                task_info = tasks[task_id]
                result = task_info["result"]
                device = task_info["device"]
                
                if result.ready():
                    completed.add(task_id)
                    
                    try:
                        if result.successful():
                            data = result.result
                            
                            # Process command results (files already saved during collection)
                            for cmd_key, cmd in self.commands.items():
                                if cmd in data.get("results", {}):
                                    cmd_result = data["results"][cmd]
                                    if cmd_result.get("success"):
                                        self.save_command_output(device, cmd_key, cmd_result)
                            
                            batch_results["successful"] += 1
                            self.metrics["successful_devices"] += 1
                            
                            print(f"    ✓ {device['hostname']} ({device['mgmt_ip']})")
                        else:
                            # Task failed
                            error = str(result.result)
                            self.log_error(device, "task_failure", error)
                            batch_results["failed"] += 1
                            self.metrics["failed_devices"] += 1
                            
                            print(f"    ✗ {device['hostname']} ({device['mgmt_ip']}): {error[:50]}")
                    
                    except Exception as e:
                        # Exception retrieving result
                        self.log_error(device, "result_error", str(e))
                        batch_results["failed"] += 1
                        self.metrics["failed_devices"] += 1
                        
                        print(f"    ✗ {device['hostname']} ({device['mgmt_ip']}): {str(e)[:50]}")
            
            # Remove completed tasks
            pending -= completed
            
            if pending:
                # Show progress
                completed_count = len(tasks) - len(pending)
                print(f"    Progress: {completed_count}/{len(tasks)} complete", end='\r')
                await asyncio.sleep(1)
        
        print()  # New line after progress
        return batch_results
    
    async def collect_rolling_window(self, devices: list[dict]):
        """
        Collect from devices using a rolling window approach.
        
        Maintains a pool of active tasks and adds new ones as soon as any complete.
        This prevents slow/stuck tasks from blocking the entire batch.
        
        Args:
            devices: List of device dictionaries to collect from
        """
        MAX_TASK_TIME = 600  # 10 minutes timeout per device
        
        # Initialize device queue
        device_queue = iter(devices)
        active_tasks = {}
        success_count = 0
        failed_count = 0
        
        print(f"\n🚀 Filling initial pool ({self.concurrency} workers)...\n")
        
        # Fill initial pool
        for _ in range(self.concurrency):
            try:
                device = next(device_queue)
                task_id, result = self.submit_device_collection(device)
                active_tasks[task_id] = {
                    "device": device,
                    "result": result,
                    "start_time": time.time()
                }
                print(f"  → Started: {device['hostname']} ({device['mgmt_ip']})")
            except StopIteration:
                break
        
        print(f"\n✓ Pool active with {len(active_tasks)} tasks")
        print(f"{'='*60}\n")
        
        # Process continuously until all devices are done
        last_progress_time = time.time()
        progress_interval = 5  # Update progress every 5 seconds
        
        while active_tasks:
            completed_task_ids = []
            
            # Check all active tasks
            for task_id, task_info in list(active_tasks.items()):
                result = task_info["result"]
                device = task_info["device"]
                elapsed = time.time() - task_info["start_time"]
                
                # Check if task is done
                if result.ready():
                    completed_task_ids.append(task_id)
                    
                    try:
                        if result.successful():
                            data = result.result
                            
                            # Process command results (files already saved during collection)
                            for cmd_key, cmd in self.commands.items():
                                if cmd in data.get("results", {}):
                                    cmd_result = data["results"][cmd]
                                    if cmd_result.get("success"):
                                        self.save_command_output(device, cmd_key, cmd_result)
                            
                            success_count += 1
                            self.metrics["successful_devices"] += 1
                            print(f"  ✓ {device['hostname']} ({device['mgmt_ip']}) - {elapsed:.1f}s")
                        else:
                            # Task failed
                            error = str(result.result)
                            self.log_error(device, "task_failure", error)
                            failed_count += 1
                            self.metrics["failed_devices"] += 1
                            print(f"  ✗ {device['hostname']} ({device['mgmt_ip']}) - FAILED: {error[:50]}")
                    
                    except Exception as e:
                        # Exception retrieving result
                        self.log_error(device, "result_error", str(e))
                        failed_count += 1
                        self.metrics["failed_devices"] += 1
                        print(f"  ✗ {device['hostname']} ({device['mgmt_ip']}) - ERROR: {str(e)[:50]}")
                    
                    # Start next device immediately
                    try:
                        next_device = next(device_queue)
                        new_task_id, new_result = self.submit_device_collection(next_device)
                        active_tasks[new_task_id] = {
                            "device": next_device,
                            "result": new_result,
                            "start_time": time.time()
                        }
                        print(f"  → Started: {next_device['hostname']} ({next_device['mgmt_ip']})")
                    except StopIteration:
                        pass  # No more devices to process
                
                # Check for timeout
                elif elapsed > MAX_TASK_TIME:
                    completed_task_ids.append(task_id)
                    failed_count += 1
                    self.metrics["failed_devices"] += 1
                    
                    error_msg = f"Task timeout after {elapsed:.1f}s (max {MAX_TASK_TIME}s)"
                    self.log_error(device, "timeout", error_msg)
                    
                    # Try to revoke the task
                    try:
                        result.revoke(terminate=True)
                    except:
                        pass
                    
                    print(f"  ⏱ {device['hostname']} ({device['mgmt_ip']}) - TIMEOUT after {elapsed:.1f}s")
                    
                    # Start next device
                    try:
                        next_device = next(device_queue)
                        new_task_id, new_result = self.submit_device_collection(next_device)
                        active_tasks[new_task_id] = {
                            "device": next_device,
                            "result": new_result,
                            "start_time": time.time()
                        }
                        print(f"  → Started: {next_device['hostname']} ({next_device['mgmt_ip']})")
                    except StopIteration:
                        pass
            
            # Remove completed tasks
            for task_id in completed_task_ids:
                del active_tasks[task_id]
            
            # Print progress periodically
            current_time = time.time()
            if current_time - last_progress_time >= progress_interval:
                total_processed = success_count + failed_count
                remaining = self.metrics["total_devices"] - total_processed
                print(f"\n📊 Progress: {total_processed}/{self.metrics['total_devices']} complete "
                      f"({success_count} ok, {failed_count} failed, "
                      f"{remaining} remaining, {len(active_tasks)} active)\n")
                last_progress_time = current_time
            
            # Small sleep to avoid busy-waiting
            await asyncio.sleep(0.5)
        
        print(f"\n{'='*60}")
        print(f"✓ All devices processed!")
        print(f"  Successful: {success_count}")
        print(f"  Failed: {failed_count}")
        print(f"  Total: {success_count + failed_count}")
        print(f"{'='*60}\n")
    
    async def run(self):
        """Run bulk collection with rolling window approach."""
        print("\n" + "="*60)
        print("Bulk Device Collection (Rolling Window)")
        print("="*60)
        
        # Check prerequisites
        if not self.check_celery_workers():
            return False
        
        # Setup
        self.setup_directories()
        
        # Fetch devices
        devices = await self.fetch_devices()
        if not devices:
            print("\n  ✗ No devices found!")
            return False
        
        self.metrics["total_devices"] = len(devices)
        self.metrics["start_time"] = datetime.now().isoformat()
        
        # Start rolling window collection
        print(f"\nStarting collection (concurrency: {self.concurrency})...")
        print(f"Total devices: {len(devices)}")
        print("="*60)
        
        start_time = time.time()
        
        # Use rolling window approach
        await self.collect_rolling_window(devices)
        
        end_time = time.time()
        duration = end_time - start_time
        
        self.metrics["end_time"] = datetime.now().isoformat()
        self.metrics["duration_seconds"] = duration
        
        # Final summary
        print("\n" + "="*60)
        print("Collection Complete")
        print("="*60)
        
        print(f"\nTotal devices: {self.metrics['total_devices']}")
        print(f"Successful: {self.metrics['successful_devices']}")
        print(f"Failed: {self.metrics['failed_devices']}")
        print(f"Duration: {duration:.1f} seconds ({duration/60:.1f} minutes)")
        
        if self.metrics['successful_devices'] > 0:
            avg_time = duration / self.metrics['successful_devices']
            print(f"Average time per device: {avg_time:.2f} seconds")
        
        print(f"\nCommands collected:")
        for cmd, count in self.metrics["commands_collected"].items():
            print(f"  {cmd}: {count}")
        
        if self.metrics["errors_by_type"]:
            print(f"\nErrors by type:")
            for error_type, count in self.metrics["errors_by_type"].items():
                print(f"  {error_type}: {count}")
        
        print(f"\nOutput directories:")
        for cmd_key, cmd_dir in self.command_dirs.items():
            print(f"  {cmd_key}: {cmd_dir}")
        print(f"  Errors: {self.error_dir}")
        
        # Save metrics
        metrics_file = self.base_dir / "metrics.json"
        with open(metrics_file, 'w') as f:
            json.dump(self.metrics, f, indent=2)
        
        print(f"\nMetrics saved to: {metrics_file}")
        
        return True


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Bulk device collection script",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Default: 10 concurrent tasks, healthcheck profile, all supported roles
  python scripts/bulk_collect.py
  
  # Custom concurrency and profile
  python scripts/bulk_collect.py --concurrency 20 --profile security_audit
  
  # Specific roles only
  python scripts/bulk_collect.py --roles EN,AN,CN --profile healthcheck
  
  # Multiple profiles (merged commands)
  python scripts/bulk_collect.py --profile healthcheck,security_audit
  
  # High concurrency for large deployments
  python scripts/bulk_collect.py --concurrency 50 --profile capacity_planning
        """
    )
    
    parser.add_argument(
        "--concurrency",
        type=int,
        default=10,
        help="Number of concurrent collection tasks (default: 10)"
    )
    
    parser.add_argument(
        "--roles",
        type=str,
        default=None,
        help=f"Comma-separated list of roles to collect (default: {','.join(DEFAULT_ROLES)})"
    )
    
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Limit number of devices to collect (for testing)"
    )
    
    parser.add_argument(
        "--profile",
        type=str,
        default="healthcheck",
        help="Command profile(s) to use (comma-separated for multiple). Default: healthcheck"
    )
    
    parser.add_argument(
        "--commands",
        type=str,
        default=None,
        help="Path to custom commands file (overrides --profile if specified)"
    )
    
    parser.add_argument(
        "--platform",
        type=str,
        default=None,
        help="Filter devices by platform (substring match, e.g., 'NCS 540', 'ASR 9')"
    )
    
    args = parser.parse_args()
    
    # Parse roles
    if args.roles:
        roles = [r.strip().upper() for r in args.roles.split(',')]
    else:
        roles = DEFAULT_ROLES
    
    # Validate concurrency
    if args.concurrency < 1:
        print(f"Error: Concurrency must be >= 1 (got {args.concurrency})")
        sys.exit(1)
    
    if args.concurrency > 100:
        print(f"Warning: High concurrency ({args.concurrency}) may overwhelm the system")
        print("Recommended: 10-50 for most deployments")
        response = input("Continue? [y/N]: ").strip().lower()
        if response != 'y':
            print("Cancelled.")
            sys.exit(0)
    
    # Load commands - either from custom file or profile(s)
    try:
        if args.commands:
            # Custom commands file specified
            commands = load_commands(args.commands)
            if not commands:
                print(f"Error: No commands found in {args.commands}")
                sys.exit(1)
            print(f"\nLoaded {len(commands)} command(s) from {args.commands}")
            for key, cmd in commands.items():
                print(f"  - {cmd}")
        else:
            # Load from profile(s)
            commands = load_profiles(args.profile)
            if not commands:
                print(f"Error: No commands found in profile(s): {args.profile}")
                sys.exit(1)
    except FileNotFoundError as e:
        print(f"Error: File not found: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"Error loading commands: {e}")
        sys.exit(1)
    
    # Run collection
    collector = BulkCollector(
        concurrency=args.concurrency,
        roles=roles,
        limit=args.limit,
        commands=commands,
        platform=args.platform
    )
    
    try:
        success = asyncio.run(collector.run())
        sys.exit(0 if success else 1)
    except KeyboardInterrupt:
        print("\n\nCollection interrupted by user.")
        print("Note: Celery tasks will continue running in the background.")
        print("To view results, check the collection_logs/ directory.")
        sys.exit(1)
    except Exception as e:
        print(f"\n\nFatal error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
